#!/bin/bash
set -euo pipefail

# Deploy AgentRay to the GCE VM (Caddy + docker-compose).
# Run from: agentray/
#
# Usage: ./infra/gce/deploy.sh --env <dev|prod> [--tag TAG] [--skip-build]
#
#   --env         Required. "dev" or "prod".
#   --tag         Image tag (default: <git-sha>-<unix-ts>).
#   --skip-build  Don't run Cloud Build; deploy an existing tag.
#
# Schema migrations are automatic: the API creates/updates Postgres and
# ClickHouse tables at startup. ClickHouse/Redis/NATS are shared single
# instances (infra/) serving both envs; Postgres is the existing Cloud SQL
# instance (secret agentray-db-url-<env>).

PROJECT_ID="lohi-dev-lohi"
ZONE="asia-southeast1-a"
VM_NAME="lohi-app"
API_IMAGE="asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker/agentray-api"
WEB_IMAGE="asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker/agentray-web"

ENV=""
TAG=""
SKIP_BUILD=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)        ENV="$2"; shift 2 ;;
    --tag)        TAG="$2"; shift 2 ;;
    --skip-build) SKIP_BUILD=true; shift ;;
    -h|--help)    sed -n '3,15p' "$0" | sed 's/^# //; s/^#$//'; exit 0 ;;
    *)            echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[ -z "$ENV" ] && { echo "ERROR: --env is required (dev or prod)" >&2; exit 1; }
[[ "$ENV" == "dev" || "$ENV" == "prod" ]] || { echo "ERROR: --env must be dev or prod" >&2; exit 1; }

case "$ENV" in
  dev)  WEB_API_URL="https://agentray-dev.lohi2.com" ;;
  prod) WEB_API_URL="https://agentray.lohi2.com" ;;
esac

GCE_DIR="$(cd "$(dirname "$0")" && pwd)"        # agentray/infra/gce
SERVICE_ROOT="$(cd "${GCE_DIR}/../.." && pwd)"  # agentray/
REPO_ROOT="$(cd "${SERVICE_ROOT}/.." && pwd)"   # repo root
CADDY_DIR="${REPO_ROOT}/infra/gce/caddy"

: "${TAG:=$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)-$(date +%s)}"

echo "==> agentray (${ENV}) → api:${TAG} web:${TAG} (web API URL: ${WEB_API_URL})"

if [ "$SKIP_BUILD" = false ]; then
  echo "==> Cloud Build (api + web)"
  gcloud builds submit "$SERVICE_ROOT" \
    --project "$PROJECT_ID" \
    --config "${SERVICE_ROOT}/infra/cloudbuild.yaml" \
    --substitutions "_API_IMAGE=${API_IMAGE},_WEB_IMAGE=${WEB_IMAGE},_TAG=${TAG},_WEB_API_URL=${WEB_API_URL}" \
    --timeout 30m --quiet
  echo "==> Re-tag :latest-${ENV}"
  gcloud container images add-tag --quiet "${API_IMAGE}:${TAG}" "${API_IMAGE}:latest-${ENV}"
  gcloud container images add-tag --quiet "${WEB_IMAGE}:${TAG}" "${WEB_IMAGE}:latest-${ENV}"
fi

echo "==> Syncing config to ${VM_NAME}"
# scp -r DIR target nests a copy inside target when it already exists, leaving
# the bind-mounted Caddyfile stale — copy caddy files into the dir instead, and
# recreate the agentray dir (secret.env is regenerated by fetch-secrets.sh).
gcloud compute ssh "$VM_NAME" --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap \
  --command "mkdir -p ~/gce/caddy && rm -rf ~/gce/agentray"
gcloud compute scp "$CADDY_DIR"/* "${VM_NAME}:~/gce/caddy/" \
  --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap
gcloud compute scp --recurse --scp-flag="-O" "$GCE_DIR" "${VM_NAME}:~/gce/agentray" \
  --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap

echo "==> Rolling on ${VM_NAME}"
gcloud compute ssh "$VM_NAME" --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap --command "
set -euo pipefail
sudo docker network inspect edge >/dev/null 2>&1 || sudo docker network create edge
sudo bash ~/gce/caddy/fetch-origin-cert.sh
sudo docker compose -f ~/gce/caddy/docker-compose.yml up -d
sudo docker exec caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || true
sudo bash ~/gce/agentray/fetch-secrets.sh '${ENV}'
sudo docker compose -f ~/gce/agentray/infra/docker-compose.yml up -d
echo 'waiting for clickhouse...'
for i in \$(seq 1 30); do
  sudo docker exec agentray-clickhouse wget --spider -q http://127.0.0.1:8123/ping 2>/dev/null && break
  sleep 2
done
CH_PW=\$(sudo grep '^CLICKHOUSE_PASSWORD=' ~/gce/agentray/infra/secret.env | cut -d= -f2-)
sudo docker exec agentray-clickhouse clickhouse-client \
  --user agentray --password \"\$CH_PW\" \
  --query 'CREATE DATABASE IF NOT EXISTS agentray_${ENV}'
sudo env AGENTRAY_TAG='${TAG}' DOCKER_CONFIG=/root/.docker \
  docker compose -f ~/gce/agentray/${ENV}/docker-compose.yml up -d --pull always
sudo docker image prune -f >/dev/null 2>&1 || true
"

echo "==> Deployed. Rollback: ./infra/gce/deploy.sh --env ${ENV} --tag <prev> --skip-build"
