#!/bin/bash
set -euo pipefail

# Deploy AgentRay to the GCE VM (Caddy + docker-compose).
# Run from: agentray/
#
# Usage: ./infra/gce/deploy.sh --env <dev|prod> [--tag TAG] [--skip-build]
#                                        [--no-gate] [--gate-timeout SECONDS]
#
#   --env           Required. "dev" or "prod".
#   --tag           Image tag (default: <git-sha>-<unix-ts>).
#   --skip-build    Don't run Cloud Build; deploy an existing tag.
#   --no-gate       Switch traffic the moment the new colour is created,
#                   without waiting for its healthcheck.
#   --gate-timeout  Seconds to wait for the new colour to go healthy (default 240).
#
# Schema migrations are automatic: the API creates/updates Postgres and
# ClickHouse tables at startup. ClickHouse/Redis/NATS are shared single
# instances (infra/) serving both envs; Postgres is the existing Cloud SQL
# instance (secret agentray-db-url-<env>).

PROJECT_ID="lohi-dev-lohi"
ZONE="asia-southeast1-a"
VM_NAME="lohi-app"
API_IMAGE="asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker/agentray-api"
WEB_IMAGE="asia-southeast1-docker.pkg.dev/${PROJECT_ID}/docker/agentray-web"

ENV=""
TAG=""
SKIP_BUILD=false
GATE=true
GATE_TIMEOUT=240

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)        ENV="$2"; shift 2 ;;
    --tag)        TAG="$2"; shift 2 ;;
    --skip-build) SKIP_BUILD=true; shift ;;
    --no-gate)      GATE=false; shift ;;
    --gate-timeout) GATE_TIMEOUT="$2"; shift 2 ;;
    -h|--help)    sed -n '3,17p' "$0" | sed 's/^# //; s/^#$//'; exit 0 ;;
    *)            echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[ -z "$ENV" ] && { echo "ERROR: --env is required (dev or prod)" >&2; exit 1; }
[[ "$ENV" == "dev" || "$ENV" == "prod" ]] || { echo "ERROR: --env must be dev or prod" >&2; exit 1; }

case "$ENV" in
  dev)  WEB_API_URL="https://agentray-dev.lohi2.com" ;;
  prod) WEB_API_URL="https://agentray.lohi2.com" ;;
esac

GCE_DIR="$(cd "$(dirname "$0")" && pwd)"        # agentray/infra/gce
SERVICE_ROOT="$(cd "${GCE_DIR}/../.." && pwd)"  # agentray/
REPO_ROOT="$(cd "${SERVICE_ROOT}/.." && pwd)"   # repo root
CADDY_DIR="${REPO_ROOT}/infra/gce/caddy"

# shellcheck source=../../../infra/gce/lib/blue-green.sh
source "${REPO_ROOT}/infra/gce/lib/blue-green.sh"
# AgentRay is two containers behind one hostname, so it owns two upstream
# snippets. Both move together: the colour is read off the api snippet, both
# containers are started on it, and both snippets flip only after BOTH report
# healthy — a half-switched hostname would serve a new dashboard against an old
# API. (agentray-web declares no healthcheck; bg_wait accepts "running" for it.)
UPSTREAM="${ENV}-agentray-api"
UPSTREAM_WEB="${ENV}-agentray-web"
# --no-gate is not "the old behaviour": traffic still moves in one atomic Caddy
# reload, it just moves before anything has vouched for the new colour.
if [ "$GATE" = false ]; then bg_wait() { :; }; fi

if [ -z "$TAG" ]; then
  if [ "$SKIP_BUILD" = true ]; then
    # No build this run, so a fresh <sha>-<ts> tag wouldn't exist in the registry;
    # reuse the last image published for this env.
    TAG="latest-${ENV}"
  else
    TAG="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)-$(date +%s)"
  fi
fi

echo "==> agentray (${ENV}) → api:${TAG} web:${TAG} (web API URL: ${WEB_API_URL})"

if [ "$SKIP_BUILD" = false ]; then
  echo "==> Cloud Build (api + web)"
  gcloud builds submit "$SERVICE_ROOT" \
    --project "$PROJECT_ID" \
    --config "${SERVICE_ROOT}/infra/cloudbuild.yaml" \
    --substitutions "_API_IMAGE=${API_IMAGE},_WEB_IMAGE=${WEB_IMAGE},_TAG=${TAG},_WEB_API_URL=${WEB_API_URL}" \
    --timeout 30m --quiet
  echo "==> Re-tag :latest-${ENV}"
  gcloud container images add-tag --quiet "${API_IMAGE}:${TAG}" "${API_IMAGE}:latest-${ENV}"
  gcloud container images add-tag --quiet "${WEB_IMAGE}:${TAG}" "${WEB_IMAGE}:latest-${ENV}"
fi

echo "==> Syncing config to ${VM_NAME}"
# scp -r DIR target nests a copy inside target when it already exists, leaving
# the bind-mounted Caddyfile stale — copy caddy files into the dir instead, and
# recreate the agentray dir (secret.env is regenerated by fetch-secrets.sh).
gcloud compute ssh "$VM_NAME" --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap \
  --command "mkdir -p ~/gce/caddy && rm -rf ~/gce/agentray"
gcloud compute scp "$CADDY_DIR"/* "${VM_NAME}:~/gce/caddy/" \
  --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap
gcloud compute scp --recurse --scp-flag="-O" "$GCE_DIR" "${VM_NAME}:~/gce/agentray" \
  --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap

echo "==> Rolling on ${VM_NAME}"
gcloud compute ssh "$VM_NAME" --zone "$ZONE" --project "$PROJECT_ID" --tunnel-through-iap --command "
set -euo pipefail
sudo docker network inspect edge >/dev/null 2>&1 || sudo docker network create edge
sudo bash ~/gce/caddy/fetch-origin-cert.sh
$(bg_seed)
$(bg_validate)
sudo docker compose -f ~/gce/caddy/docker-compose.yml up -d
sudo docker exec caddy caddy reload --config /etc/caddy/Caddyfile 2>/dev/null || true
sudo bash ~/gce/agentray/fetch-secrets.sh '${ENV}'
sudo docker compose -f ~/gce/agentray/infra/docker-compose.yml up -d
echo 'waiting for clickhouse...'
for i in \$(seq 1 30); do
  sudo docker exec agentray-clickhouse wget --spider -q http://127.0.0.1:8123/ping 2>/dev/null && break
  sleep 2
done
CH_PW=\$(sudo grep '^CLICKHOUSE_PASSWORD=' ~/gce/agentray/infra/secret.env | cut -d= -f2-)
sudo docker exec agentray-clickhouse clickhouse-client \
  --user agentray --password \"\$CH_PW\" \
  --query 'CREATE DATABASE IF NOT EXISTS agentray_${ENV}'
$(bg_pick "$UPSTREAM")
BG_NEW_API=${ENV}-agentray-api-\$BG_COLOR
BG_NEW_WEB=${ENV}-agentray-web-\$BG_COLOR
BG_OLD=\${BG_OLD_COLOR:+${ENV}-agentray-api-\$BG_OLD_COLOR ${ENV}-agentray-web-\$BG_OLD_COLOR}
BG_LEGACY=\${BG_LEGACY:+${ENV}-agentray-api ${ENV}-agentray-web}
sudo env AGENTRAY_TAG='${TAG}' DOCKER_CONFIG=/root/.docker \
  docker compose -f ~/gce/agentray/${ENV}/docker-compose.yml up -d --pull always \
  agentray-api-\$BG_COLOR agentray-web-\$BG_COLOR
$(bg_wait "$GATE_TIMEOUT" "\$BG_NEW_API \$BG_NEW_WEB")
$(bg_switch "$UPSTREAM" "\$BG_NEW_API" 8080)
$(bg_switch "$UPSTREAM_WEB" "\$BG_NEW_WEB" 3200)
$(bg_park "\$BG_OLD \$BG_LEGACY")
sudo docker image prune -f >/dev/null 2>&1 || true
"

echo "==> Deployed. Rollback (seconds, exact same image): ../infra/gce/rollback.sh --service agentray --env ${ENV}"
echo "    The previous colour is parked, not deleted. Add --dry-run to see what it returns to."
