// Development-only translation of the locked TypeBox format expressions.
// Native Go loads only the generated Go literals, never TypeScript or this file.
import { readFileSync, writeFileSync } from "node:fs";
const source = new URL("../../../third_party/pi/node_modules/typebox/", import.meta.url);
const version = JSON.parse(readFileSync(new URL("package.json", source), "utf8")).version;
if (version !== "1.3.27") throw new Error(`Review format translation for TypeBox ${version}`);
const formats = ["uuid", "ipv4", "ipv6", "duration", "email", "idn-email", "json-pointer", "json-pointer-uri-fragment", "relative-json-pointer", "uri", "uri-reference", "uri-template", "date", "time"];
const entries = formats.map(name => {
  const code = readFileSync(new URL(`build/format/${name.replaceAll("-", "_")}.mjs`, source), "utf8");
  const match = /^const \w+ = \/(.*)\/([iu]*);$/m.exec(code);
  if (!match) throw new Error(`Missing ${name} expression`);
  const flags = "regexp2.ECMAScript" + (match[2].includes("i") ? "|regexp2.IgnoreCase" : "") + (match[2].includes("u") ? "|regexp2.Unicode" : "");
  const compile = match[2].includes("u") ? "mustCompileArgumentUnicodeFormat" : "regexp2.MustCompile";
  return `\t${JSON.stringify(name)}: ${compile}(${JSON.stringify(match[1])}, ${flags}),`;
});
const output = `// Code generated by testdata/generate-format-patterns.ts; DO NOT EDIT.
// Expressions from TypeBox ${version}; see LICENSE.typebox.
package engine

import "github.com/dlclark/regexp2"

var argumentFormatPatterns = map[string]*regexp2.Regexp{
${entries.join("\n")}
}
`;
// gofmt is part of generation so --check compares the committed representation.
const formatted = Bun.spawnSync(["gofmt"], {stdin: new TextEncoder().encode(output)});
if (formatted.exitCode !== 0) throw new Error(new TextDecoder().decode(formatted.stderr));
const actual = new TextDecoder().decode(formatted.stdout);
const destination = new URL("../argument_format_patterns.go", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(destination, "utf8") !== actual) throw new Error("Format expressions changed; regenerate and review");
} else writeFileSync(destination, actual);
console.log(`Verified ${formats.length} TypeBox ${version} format expressions`);
