// Development-only extraction of the RegExp property sets used by Pi/TypeBox.
// Go consumes generated ranges and never launches this script at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import { manifest } from "./oracle.ts";

if (Bun.version !== "1.3.14" || process.versions.unicode !== "15.1") {
  throw new Error("Review Unicode parity before changing the Bun 1.3.14 / Unicode 15.1 oracle");
}
function rows(file: string): string[][] {
  const source = readFileSync(new URL(`unicode-15.1/${file}.txt`, import.meta.url), "utf8");
  if (!source.startsWith(`# ${file}-15.1.0.txt`)) throw new Error(`Unexpected Unicode data: ${file}`);
  return source.split("\n").map(line => line.split("#")[0].trim()).filter(Boolean)
    .map(line => line.split(";").map(part => part.trim()).filter(Boolean));
}
const aliases = new Map<string, string>();
function add(alias: string, canonical: string) {
  // UCD also defines properties/aliases not admitted by ECMAScript. Ask the
  // same constructor as TypeBox's IsRegex, without loose alias matching.
  try { new RegExp(`\\p{${alias}}`, "u"); new RegExp(`\\p{${canonical}}`, "u"); }
  catch { return; }
  aliases.set(alias, canonical);
}
for (const row of rows("PropertyAliases")) {
  for (const alias of row) add(alias, row[1]);
}
for (const name of ["ASCII", "Any", "Assigned"]) add(name, name);
for (const [property, short, long, ...extra] of rows("PropertyValueAliases")) {
  const names = [short, long, ...extra];
  if (property === "gc") {
    for (const name of names) {
      add(name, `General_Category=${long}`);
      for (const prefix of ["gc", "General_Category"]) add(`${prefix}=${name}`, `General_Category=${long}`);
    }
  }
  if (property === "sc") {
    for (const name of names) {
      for (const [prefix, canonical] of [["sc", "Script"], ["Script", "Script"], ["scx", "Script_Extensions"], ["Script_Extensions", "Script_Extensions"]]) {
        add(`${prefix}=${name}`, `${canonical}=${long}`);
      }
    }
  }
}
const codepoints = Array.from({length: 0x110000}, (_, code) => String.fromCodePoint(code));
const canonicalNames = [...new Set(aliases.values())].sort();
const ranges = new Map<string, number[]>();
for (let i = 0; i < canonicalNames.length; i++) {
  const name = canonicalNames[i];
  const pattern = new RegExp(`^\\p{${name}}$`, "u");
  const set: number[] = [];
  let start = -1;
  for (let code = 0; code < codepoints.length; code++) {
    if (pattern.test(codepoints[code])) {
      if (start === -1) start = code;
    } else if (start !== -1) {
      set.push(start, code - 1);
      start = -1;
    }
  }
  if (start !== -1) set.push(start, 0x10ffff);
  ranges.set(name, set);
  if ((i + 1) % 50 === 0) console.log(`Extracted ${i + 1}/${canonicalNames.length} Unicode property sets`);
}
const output = `// Code generated by testdata/generate-unicode-properties.ts; DO NOT EDIT.
// Pi ${manifest.commit}; Bun 1.3.14; Unicode 15.1.
// Property aliases: Unicode 15.1 UCD; see testdata/unicode-15.1/LICENSE.txt.
package engine

var argumentUnicodePropertyAliases = map[string]string{
${[...aliases].sort(([a],[b])=>a<b?-1:a>b?1:0).map(([alias, canonical])=>`\t${JSON.stringify(alias)}: ${JSON.stringify(canonical)},`).join("\n")}
}

// Each pair is an inclusive code-point interval, in ascending order.
var argumentUnicodePropertyRanges = map[string][]rune{
${[...ranges].map(([name, set])=>`\t${JSON.stringify(name)}: {\n${Array.from({length: Math.ceil(set.length / 16)}, (_, i)=>`\t\t${set.slice(i*16,i*16+16).map(code=>`0x${code.toString(16)}`).join(", ")},`).join("\n")}\n\t},`).join("\n")}
}
`;
const formatted = Bun.spawnSync(["gofmt"], {stdin: new TextEncoder().encode(output)});
if (formatted.exitCode !== 0) throw new Error(new TextDecoder().decode(formatted.stderr));
const actual = new TextDecoder().decode(formatted.stdout);
const destination = new URL("../argument_unicode_properties.go", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(destination, "utf8") !== actual) throw new Error("Unicode property data changed; regenerate and review");
} else writeFileSync(destination, actual);
// Independently ask RegExp about boundaries, interiors and both sides of every
// interval. Go tests exercise the actual compiled matcher against these probes.
const cases = [...ranges].map(([property, set]) => {
  const samples = new Set<number>([0, 0x7f, 0x80, 0xffff, 0x10000, 0x10ffff]);
  for (let i = 0; i < set.length; i += 2) {
    const start = set[i], end = set[i + 1];
    for (const code of [start - 1, start, Math.floor((start + end) / 2), end, end + 1]) {
      // Go strings cannot represent a lone UTF-16 surrogate. The generated
      // ranges retain them, but matching that input remains outside this test.
      if (code >= 0 && code <= 0x10ffff && !(code >= 0xd800 && code <= 0xdfff)) samples.add(code);
    }
  }
  const pattern = new RegExp(`^\\p{${property}}$`, "u");
  return {property, aliases: [...aliases].filter(([,name])=>name === property).map(([alias])=>alias).sort(),
    probes: [...samples].sort((a,b)=>a-b).map(code=>[code, pattern.test(String.fromCodePoint(code))])};
});
// Capture identifiers have a separate JavaScriptCore grammar: property
// membership alone does not prove name admission. Probe all boundaries and
// interiors of the relevant categories, plus the ID_Start/Continue exceptions.
const identifierProperties = new Set([
  "General_Category=Letter", "General_Category=Letter_Number",
  "General_Category=Nonspacing_Mark", "General_Category=Spacing_Mark",
  "General_Category=Decimal_Number", "General_Category=Connector_Punctuation",
  "ID_Start", "ID_Continue",
]);
const identifierPoints = new Set(Array.from({length: 128}, (_, i) => i));
for (const row of cases) if (identifierProperties.has(row.property)) {
  for (const [code] of row.probes) identifierPoints.add(code as number);
}
function captureAdmits(code: number, prefix: string): boolean {
  try {
    const match = new RegExp(`(?<${prefix}\\u{${code.toString(16)}}>x)`, "u").exec("x");
    return Object.hasOwn(match?.groups ?? {}, prefix + String.fromCodePoint(code));
  }
  catch { return false; }
}
const captureNames = [...identifierPoints].sort((a,b)=>a-b)
  .map(code => [code, captureAdmits(code, ""), captureAdmits(code, "a")]);
const fixture = `{
  "upstreamCommit": ${JSON.stringify(manifest.commit)},
  "bun": ${JSON.stringify(Bun.version)},
  "unicode": ${JSON.stringify(process.versions.unicode)},
  "captureNames": ${JSON.stringify(captureNames)},
  "cases": [
${cases.map(row=>"    "+JSON.stringify(row)).join(",\n")}
  ]
}
`;
const fixtureDestination = new URL("pi-unicode-properties.json", import.meta.url);
if (process.argv.includes("--check")) {
  if (readFileSync(fixtureDestination, "utf8") !== fixture) throw new Error("Unicode property probes changed; regenerate and review");
} else writeFileSync(fixtureDestination, fixture);
console.log(`Verified ${aliases.size} aliases and ${ranges.size} Unicode property sets across all 1,114,112 code points; ${cases.reduce((sum, row)=>sum+row.probes.length,0)} matching probes; ${captureNames.length} capture-name probes`);
